#!/bin/bash
set -e

APP=${APP:-GoogleDriveSync}
BUILD_DIR=${BUILD_DIR:-.build/debug}
CODESIGN_ID=${CODESIGN_ID:-LocalDevCert}

BUNDLE_NAME="${APP}.app"
MACOS_DIR="${BUNDLE_NAME}/Contents/MacOS"
RESOURCES_DIR="${BUNDLE_NAME}/Contents/Resources"

echo "Bundling ${APP}..."

mkdir -p "${MACOS_DIR}"
mkdir -p "${RESOURCES_DIR}"

# 1. Copy Info.plist
cp GoogleDriveSync/Info.plist "${BUNDLE_NAME}/Contents/Info.plist"

# Update Info.plist variables
plutil -replace CFBundleExecutable -string "${APP}" "${BUNDLE_NAME}/Contents/Info.plist" 2>/dev/null || true
plutil -replace CFBundleIdentifier -string "com.saihgupr.GoogleDriveSync" "${BUNDLE_NAME}/Contents/Info.plist" 2>/dev/null || true
plutil -replace CFBundleName -string "${APP}" "${BUNDLE_NAME}/Contents/Info.plist" 2>/dev/null || true
plutil -replace CFBundleIconFile -string "AppIcon" "${BUNDLE_NAME}/Contents/Info.plist" 2>/dev/null || true

# 2. Copy executable
cp "${BUILD_DIR}/${APP}" "${MACOS_DIR}/"

# 3. Generate AppIcon.icns
ICONSET_TMP="AppIcon.iconset"
mkdir -p "${ICONSET_TMP}"
cp GoogleDriveSync/Assets.xcassets/AppIcon.appiconset/icon_*.png "${ICONSET_TMP}/" 2>/dev/null || true
if [ "$(ls -A ${ICONSET_TMP})" ]; then
    iconutil -c icns "${ICONSET_TMP}" -o "${RESOURCES_DIR}/AppIcon.icns" 2>/dev/null || true
fi
rm -rf "${ICONSET_TMP}"

# 4. Copy resource bundle if generated by SPM
if [ -d "${BUILD_DIR}/${APP}_${APP}.bundle" ]; then
    cp -R "${BUILD_DIR}/${APP}_${APP}.bundle" "${RESOURCES_DIR}/"
fi

# 5. Codesign
ENTITLEMENTS="GoogleDriveSync/GoogleDriveSync.entitlements"
ENT_FLAG=""
if [ -f "${ENTITLEMENTS}" ]; then
    ENT_FLAG="--entitlements ${ENTITLEMENTS}"
fi

if [ -n "${CODESIGN_ID}" ] && security find-identity -p codesigning -v | grep -q "${CODESIGN_ID}"; then
    echo "Signing ${BUNDLE_NAME} with '${CODESIGN_ID}'..."
    codesign --force --deep --sign "${CODESIGN_ID}" ${ENT_FLAG} "${BUNDLE_NAME}"
else
    echo "No codesigning identity '${CODESIGN_ID}' found in keychain. Signing with ad-hoc signature..."
    codesign --force --deep --sign - ${ENT_FLAG} "${BUNDLE_NAME}"
fi

echo "Bundle completed successfully: ${BUNDLE_NAME}"
